
language: node_js

node_js:
  - "8.9.4"

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/waiter_db

before_script:
  - psql -c 'create database waiter_db;' -U postgres
  - psql -U postgres -d waiter_db -a -f tables.sql

addons:
    apt:
    packages:
    - postgresql-server-dev-9.2